apiVersion: v1
data:
  MONGO_PASSWORD: _{_MONGO_PASSWORD_}_
  MONGO_URI: _{_MONGO_URI_}_
  MONGO_USERNAME: _{_MONGO_USERNAME_}_
kind: Secret
metadata:
  name: mongo-db-creds
  namespace: _{_NAMESPACE_}_