name: Solar System Workflow

on: 
  workflow_dispatch:
    
jobs:
    unit-testing:
        name: Unit Testing        
        strategy:
          matrix:
            os: [windows-latest, ubuntu-latest]             
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          continue-on-error: true
          with:
            name: Mocha-Test-Result
            path: test-results.xml
