name: Solar System Workflow

on: 
  workflow_dispatch:
    
jobs:
    build: 
      name: build
      runs-on: ubuntu-latest
      steps: 
        - name: clone repository
          env:
            TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git clone https://$TOKEN@github.com/${{ github.repository_owner }}/github-actions-solar-system.git

        - name: verify Docker version
          run: |
            docker --version
            docker info

        - name: Build Docker image
          run: |
            docker build \
              --file ./github-actions-solar-system/Dockerfile \
              --build-arg MONGO_URI="${{ vars.MONGO_URI }}" \
              --build-arg MONGO_USERNAME="${{ vars.MONGO_USERNAME }}" \
              --build-arg MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
              -t solar-system:"${{ github.sha }}" .
        - name: run test container
          run: |
            docker run -it -d --name my-running-app -p 3000:3000 solar-system:${{ github.sha }}
            docker ps -a
            sleep 15
            curl -sSf http://localhost:3000/ | grep "<html>" || exit 1
            
            
        # || (docker logs my-running-app && exit 1)


        # - name: login to docker hub
        #   uses: docker/login-action@v3
        #   with:
        #     username: ${{ vars.DOCKERHUB_USERNAME }}
        #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # unit-testing:
    #     name: Unit Testing                          
    #     runs-on: ubuntu-latest
    #     # Expose step outputs as job outputs
    #     outputs: 
    #       my-step-output-1: ${{ steps.output-step-1.outputs.expectedout }}
    #       my-step-output-2: ${{ steps.output-step-2.outputs.expectedout }}
    #     steps:
    #     - name: Checkout Repository
    #       uses: actions/checkout@v4

    #     - name: Setup NodeJS Version
    #       uses: actions/setup-node@v4
    #       with:
    #         node-version: 20

    #     - name: Cache NPM dependencies
    #       id: cache-npm-dependencies
    #       uses: actions/cache@v4
    #       with:
    #         path: ~/.npm
    #         key: ${{ runner.os }}-3rdparty-dependencies-${{ hashFiles('package-lock.json') }}
    
    #     - name: Install Dependencies
    #       run: npm install
    
    #     - name: Unit Testing
    #       run: npm test
        
    #     - name: Output step-1
    #       id: output-step-1
    #       run: 
    #         echo "expectedout=Hello" >> "$GITHUB_OUTPUT"
    #     - name: Output step-2
    #       id: output-step-2
    #       run: 
    #         echo "expectedout=world" >> "$GITHUB_OUTPUT"
          
    #     - name: Archive Test Result
    #       uses: actions/upload-artifact@v4
    #       continue-on-error: true
    #       with:
    #         name: Mocha-Test-Result
    #         path: test-results.xml
    # code-coverage: 
    #   name: code-coverage
    #   runs-on: ubuntu-latest
    #   needs: unit-testing
    #   steps:
    #     - name: get output - from previous job
    #       run: echo ${{ needs.unit-testing.outputs.my-step-output-1 }} ${{ needs.unit-testing.outputs.my-step-output-2 }} 

    #     - name: downloading artifact
    #       uses: actions/download-artifact@v4
    #       # with:
    #       #   name: my-artifact
    #     - name: Display structure of downloaded files
    #       run: ls -R
